<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * componenteRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class componenteRepository extends EntityRepository
{
    public function getAllProductos()
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('s')
            ->from('AppBundle:tipoComponente', 's');
//      ->where($qb->expr()->eq('s.estado', ':prmServicio'))
//      ->setParameter('prmServicio', 1);

        return $qb;
    }
}
