<?php

namespace AppBundle\Repository;

/**
 * GrupoUsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrupoUsuarioRepository extends \Doctrine\ORM\EntityRepository
{
}
