# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
    #        Symfony\Component\Security\Core\User\User:
    #            algorithm: bcrypt
    #            cost: 12

            AppBundle\Entity\Administracion\Usuario: md5
            AppBundle\Form\ChangePassword: md5

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_user:
            entity: { class: AppBundle:Administracion\Usuario, property: username }
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            guard:
                authenticators:
                     - app.security.login_form_authenticator
            logout:
                path: /logout
                target: /login
                invalidate_session: true
            form_login:
                login_path: /login
                check_path: /login_check
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
    access_control:
       # - { path: ^/admin, roles: 'ROLE_ADMIN'}
        - { path: ^/reportes, roles: 'ROLE_USER,ROLE_TECNICO,ROLE_ADMIN,ROLE_JEFE_DEP,ROLE_AFT'}
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
