<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * departamentoRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class departamentoRepository extends EntityRepository
{
  /**
   * Devolver los departamentos
   */
  public function findDepartamentos()
  {
    $qb = $this->getEntityManager()->createQueryBuilder();
    $qb->select('p')
      ->from('AppBundle:departamento', 'p')
    ;
    return $qb;
  }
}
