<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * equipoAssetsRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class equipoAssetsRepository extends EntityRepository
{
}
