<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * equipo_de_inventariosRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class equipo_de_inventariosRepository extends EntityRepository
{
}
