<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * movimientoI_AFRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class movimientoI_AFRepository extends EntityRepository
{
}
