<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * productoAssetsRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class productoAssetsRepository extends EntityRepository
{
  public function getAllProductos()
  {
    $qb = $this->getEntityManager()->createQueryBuilder();
    $qb->select('s')
      ->from('AppBundle:productoAssets', 's');
    //  ->where(s.existencia)
   // ->where('s.existencia!=0');
      //->setParameter('prmServicio', 1);

    return $qb;
  }
    public function getProductosEnExistencia()
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('s')
            ->from('AppBundle:productoAssets', 's')
        ->where('s.existencia!=0');
        //  ->where(s.existencia)
        // ->where('s.existencia!=0');
        //->setParameter('prmServicio', 1);

        return $qb;
    }
}
