<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * solicitudRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class solicitudRepository extends EntityRepository
{
}
